image: denoland/deno:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - deno test --allow-net --allow-env
    - deno check supabase/functions/check-email-exists/index.ts
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - curl -X POST -H "Authorization: Bearer $DEPLOY_TOKEN" -d "{\"ref\": \"main\", \"variables\": {\"SUPABASE_URL\": \"$SUPABASE_URL\", \"SUPABASE_SERVICE_ROLE_KEY\": \"$SUPABASE_SERVICE_ROLE_KEY\"}}" https://api.deno.dev/v1/projects/<your-deno-deploy-project-id>/deployments
  only:
    - main