// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppmlqsfcpjedjitnamti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwbWxxc2ZjcGplZGppdG5hbXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDQ5MzQsImV4cCI6MjA1OTc4MDkzNH0.GIJXQuZhZ-3s-Uo1SvKIcnAjvntLP6D3I8kFOTVygHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);