name: Deploy to GitHub Pages and Deno Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set environment variables
        run: |
          echo "VITE_BASE_URL=${{ vars.VITE_BASE_URL || '/' }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
      - name: Install frontend dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.3
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "enugu-waste-watch"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "dist"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}